"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import plans_bandwidth as shared_plans_bandwidth
from typing import Optional


@dataclasses.dataclass
class GetPlansBandwidthResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    plans_bandwidth: Optional[shared_plans_bandwidth.PlansBandwidth] = dataclasses.field(default=None)
    r"""Success"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    